# Data preprocessing Movie_sample_dataset using Python

## mengimport library

disini kita mengimport beberapa library yang dibutuhkan untuk melakukan preprocessing data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## mengimport the Dataset untuk kemudian dianalisa

disini kita mengimport untuk membaca dataset movie sample dataset yang kemudian selanjutnya kita prepreocessing

In [11]:
df = pd.read_csv('movie_sample_dataset.csv', encoding='utf-8')
df.head()

color      director_name  duration        gross  \
0   Color    Martin Scorsese       240  116866727.0   
1   Color        Shane Black       195  408992272.0   
2  color   Quentin Tarantino       187   54116191.0   
3   Color   Kenneth Lonergan       186      46495.0   
4   Color      Peter Jackson       186  258355354.0   

                                 genres                          movie_title  \
0          Biography|Comedy|Crime|Drama              The Wolf of Wall Street   
1               Action|Adventure|Sci-Fi                           Iron Man 3   
2  Crime|Drama|Mystery|Thriller|Western                    The Hateful Eight   
3                                 Drama                             Margaret   
4                     Adventure|Fantasy  The Hobbit: The Desolation of Smaug   

   title_year language country       budget  imdb_score  \
0        2013  English     USA  100000000.0         8.2   
1        2013  English     USA  200000000.0         7.2   
2        2015  English     USA   44000000.0         7.9   
3        2011  English     usa   14000000.0         6.5   
4        2013  English     USA  225000000.0         7.9   

                                              actors  movie_facebook_likes  
0  Leonardo DiCaprio,Matthew McConaughey,Jon Favreau                138000  
1          Robert Downey Jr.,Jon Favreau,Don Cheadle                 95000  
2          Craig Stark,Jennifer Jason Leigh,Zoë Bell                114000  
3        Matt Damon,Kieran Culkin,John Gallagher Jr.                     0  
4              Aidan Turner,Adam Brown,James Nesbitt                 83000

## Menjabarkan dataset

In [12]:
df.drop(['color','language'], axis=1, inplace=True)
df.head()

director_name  duration        gross  \
0    Martin Scorsese       240  116866727.0   
1        Shane Black       195  408992272.0   
2  Quentin Tarantino       187   54116191.0   
3   Kenneth Lonergan       186      46495.0   
4      Peter Jackson       186  258355354.0   

                                 genres                          movie_title  \
0          Biography|Comedy|Crime|Drama              The Wolf of Wall Street   
1               Action|Adventure|Sci-Fi                           Iron Man 3   
2  Crime|Drama|Mystery|Thriller|Western                    The Hateful Eight   
3                                 Drama                             Margaret   
4                     Adventure|Fantasy  The Hobbit: The Desolation of Smaug   

   title_year country       budget  imdb_score  \
0        2013     USA  100000000.0         8.2   
1        2013     USA  200000000.0         7.2   
2        2015     USA   44000000.0         7.9   
3        2011     usa   14000000.0         6.5   
4        2013     USA  225000000.0         7.9   

                                              actors  movie_facebook_likes  
0  Leonardo DiCaprio,Matthew McConaughey,Jon Favreau                138000  
1          Robert Downey Jr.,Jon Favreau,Don Cheadle                 95000  
2          Craig Stark,Jennifer Jason Leigh,Zoë Bell                114000  
3        Matt Damon,Kieran Culkin,John Gallagher Jr.                     0  
4              Aidan Turner,Adam Brown,James Nesbitt                 83000

## Mencari missing Values

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   director_name         88 non-null     object 
 1   duration              99 non-null     int64  
 2   gross                 91 non-null     float64
 3   genres                98 non-null     object 
 4   movie_title           99 non-null     object 
 5   title_year            99 non-null     int64  
 6   country               99 non-null     object 
 7   budget                95 non-null     float64
 8   imdb_score            99 non-null     float64
 9   actors                99 non-null     object 
 10  movie_facebook_likes  99 non-null     int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 8.6+ KB


## Menangani error dan missing Values

Mengekstrack nilai kosong pada tiap tiap variabel yang ada pada dataset

### 1. director_name (11 Missing Values)

In [15]:
#Total Number of Missing NA
print(df.isnull().sum())

director_name           11
duration                 0
gross                    8
genres                   1
movie_title              0
title_year               0
country                  0
budget                   4
imdb_score               0
actors                   0
movie_facebook_likes     0
dtype: int64


### 2. Duration (Outliers)

In [16]:
df['director_name'].unique()

array(['Martin Scorsese', 'Shane Black', 'Quentin Tarantino',
       'Kenneth Lonergan', 'Peter Jackson', nan, 'Edward Hall',
       'Joss Whedon', 'Tom Tykwer', 'Null', 'Christopher Spencer',
       'Christopher Nolan', 'F. Gary Gray', 'Richard Linklater',
       'Michael Bay', 'Tom Hooper', 'Kathryn Bigelow', 'Ridley Scott',
       'Denis Villeneuve', 'Gnana Rajasekaran', 'Marc Webb', 'Nan',
       'Mike Leigh', 'Gore Verbinski', 'David Fincher', 'Bryan Singer',
       'Jay Oliva', 'Paul Thomas Anderson', 'Sam Mendes',
       'Michael Patrick King', 'Tate Taylor', 'Francis Lawrence',
       'Steven Spielberg', 'Guillaume Canet', 'Adam McKay', 'Zack Snyder',
       'Baz Luhrmann', 'Timur Bekmambetov', 'Justin Chadwick',
       'Oliver Stone', 'David Dobkin', 'Ryan Murphy', 'James Wan',
       'Derek Cianfrance', "Gavin O'Connor", 'Gary Ross',
       'Terrence Malick', 'Robert Zemeckis', 'Darren Aronofsky',
       'James Mangold', 'Daniel Espinosa', 'Walter Salles',
       'Angelina Jo

### 3. Gross (8 Missing Values)

In [18]:
df['duration'].unique()

array([240, 195, 187, 186, 183, -50, 180, 173, 172, 158, 170, 169, 167,
       165, 580, 164, 157, 156, 154, 153, 151, 150, 650, 149, 148, 147,
       146, 144, 143, 142, 141, 140, 139, 138, 137, 136, 135, 134,   5],
      dtype=int64)

### 4. genres (1 Missing Values)

In [19]:
df['gross'].unique()

array([1.16866727e+08, 4.08992272e+08, 5.41161910e+07, 4.64950000e+04,
       2.58355354e+08, 3.30249062e+08, 3.03001229e+08,            nan,
       6.23279547e+08, 2.70985800e+07, 1.02515793e+08, 5.96961760e+07,
       1.87991439e+08, 1.61029270e+08, 2.53592000e+07, 1.62804648e+08,
       2.45428137e+08, 4.48130642e+08, 2.55108370e+08, 1.48775460e+08,
       9.57207160e+07, 1.05219735e+08, 1.83635922e+08, 3.52358779e+08,
       6.09628780e+07, 2.62030663e+08, 2.28430993e+08, 6.50070450e+07,
       1.82204440e+08, 3.95850000e+06, 8.92899100e+07, 1.67735396e+08,
       2.33914986e+08, 2.92568851e+08, 8.09331800e+06, 2.00074175e+08,
       4.07197282e+08, 9.53289370e+07, 1.69705587e+08, 4.24645577e+08,
       7.98833590e+07, 5.28224180e+07, 4.12290000e+04, 1.63772740e+07,
       1.54985087e+08, 2.17531200e+06, 2.91021565e+08, 3.04360277e+08,
       1.44812796e+08, 7.23060650e+07, 2.02853933e+08, 4.07999255e+08,
       4.58991599e+08, 8.32474800e+06, 4.73075500e+07, 4.71050850e+07,
      

### 5. title_year (Outliers)

In [20]:
df['gross'].fillna(0, inplace=True)

### 6. Country (Uppercase, Different Format)

In [21]:
df['genres'].unique()

array(['Biography|Comedy|Crime|Drama', 'Action|Adventure|Sci-Fi',
       'Crime|Drama|Mystery|Thriller|Western', 'Drama',
       'Adventure|Fantasy', 'Drama|Romance', 'Drama|Sci-Fi',
       'Crime|Drama|Mystery|Thriller', nan, 'Adventure|Drama|Sci-Fi',
       'Biography|Crime|Drama|History|Music', 'Drama|Western',
       'Action|Thriller', 'Drama|Musical|Romance',
       'Drama|History|Thriller', 'Action|Adventure|Drama|History',
       'Adventure|Drama|Thriller|Western', 'Biography|Drama|History',
       'Action|Adventure|Fantasy', 'Action|Adventure|Drama',
       'Biography|Drama|History|War', 'Action|Adventure|Western',
       'Action|Adventure|Fantasy|Sci-Fi|Thriller',
       'Action|Animation|Crime|Sci-Fi|Thriller',
       'Action|Adventure|Sci-Fi|Thriller',
       'Comedy|Crime|Drama|Mystery|Romance', 'Action|Adventure|Thriller',
       'Comedy|Drama|Romance', 'Adventure|Sci-Fi|Thriller', 'Drama|War',
       'Action|Drama|Thriller|War', 'Crime|Drama|Thriller', 'Comedy',
       'A

In [23]:
pd.set_option('display.max_rows', None)
df['genres']

0                 Biography|Comedy|Crime|Drama
1                      Action|Adventure|Sci-Fi
2         Crime|Drama|Mystery|Thriller|Western
3                                        Drama
4                            Adventure|Fantasy
5                      Action|Adventure|Sci-Fi
6                            Adventure|Fantasy
7                                Drama|Romance
8                      Action|Adventure|Sci-Fi
9                      Action|Adventure|Sci-Fi
10                                Drama|Sci-Fi
11                Crime|Drama|Mystery|Thriller
12                                         NaN
13                      Adventure|Drama|Sci-Fi
14         Biography|Crime|Drama|History|Music
15                                       Drama
16                               Drama|Western
17                     Action|Adventure|Sci-Fi
18                             Action|Thriller
19                           Adventure|Fantasy
20                       Drama|Musical|Romance
21           

In [24]:
df['title_year'].unique()

array([2013, 2015, 2011,  202, 2012, 2014, 2010, 2016,  205], dtype=int64)

In [25]:
df['country'].unique()

array(['USA', 'usa', 'UK', 'Germany', 'New Zealand', 'India',
       'United States', 'France', 'Australia', 'Czech Republic',
       'Kyrgyzstan', 'Canada'], dtype=object)

In [26]:
df['country'].unique()

array(['USA', 'usa', 'UK', 'Germany', 'New Zealand', 'India',
       'United States', 'France', 'Australia', 'Czech Republic',
       'Kyrgyzstan', 'Canada'], dtype=object)

### 7. Budget (Outlier)

Disini kita melihat garis besar outlier dari rentang dari budget

In [27]:
df['budget'].unique()

array([1.000e+08, 2.000e+08, 4.400e+07, 1.400e+07, 2.250e+08, 2.500e+08,
       1.800e+08,       nan, 2.200e+08, 1.020e+08, 9.000e+07, 2.200e+07,
       1.650e+08, 2.800e+07, 4.000e+06, 2.100e+08, 6.100e+07, 4.000e+07,
       1.350e+08, 1.950e+08, 4.600e+07, 2.300e+08, 1.080e+08, 1.400e+08,
       6.500e+07, 2.150e+08, 3.500e+06, 1.600e+08, 2.000e+07, 2.450e+08,
       2.500e+07, 1.300e+08, 6.600e+07, 5.000e+07, 2.550e+07, 3.200e+07,
       1.780e+08, 1.050e+08, 1.735e+04, 7.800e+07, 3.500e+07, 4.500e+07,
       6.000e+07, 1.900e+08, 1.500e+07, 8.500e+07, 3.000e+07, 3.100e+07,
       1.250e+08, 8.000e+07, 1.200e+08, 1.700e+08, 7.500e+07, 7.000e+07,
       1.400e+06, 5.500e+07, 6.800e+07])

### 8. Imdb_score (Outlier)

Disini kita melihat garis besar outlier dari rentang dari imdb_score

In [28]:
df['imdb_score'].unique()

array([ 8.2,  7.2,  7.9,  6.5,  6.9,  8.1, -7.5,  7.8,  5.6,  8.6,  8. ,
        8.5,  5.7,  7.5,  7.6,  7.4,  6.7,  6.3,  7. ,  6.1,  6.8,  8.4,
        8.8,  4.3,  7.1,  7.3,  3. ,  6. ,  5.8,  5.3,  6.4,  6.6, -1.2,
        5.9,  8.7])

In [29]:
df['imdb_score'].unique()

array([ 8.2,  7.2,  7.9,  6.5,  6.9,  8.1, -7.5,  7.8,  5.6,  8.6,  8. ,
        8.5,  5.7,  7.5,  7.6,  7.4,  6.7,  6.3,  7. ,  6.1,  6.8,  8.4,
        8.8,  4.3,  7.1,  7.3,  3. ,  6. ,  5.8,  5.3,  6.4,  6.6, -1.2,
        5.9,  8.7])